import type { Molecule } from "../bindings";

/**
 * Formats an atom label for display in the 3D viewer.
 * @param displayIndex 1‑based index displayed to the user
 * @param formalCharge formal charge of the atom (may be undefined)
 */
export function formatAtomLabel(displayIndex: number, formalCharge: number) {
  formalCharge = formalCharge ?? 0;
  if (formalCharge === 0) return String(displayIndex);
  const magnitude = Math.abs(formalCharge);
  const sign = formalCharge > 0 ? "+" : "-";
  return `${displayIndex} ${magnitude === 1 ? sign : `${magnitude}${sign}`}`;
}

/**
 * Returns a human‑readable string describing the selected atoms.
 */
export function formatSelectedDisplayAtoms(molecule: Molecule, selectedAtomIds: number[]) {
  if (selectedAtomIds.length === 0) return "No selection";
  const displayIds = selectedAtomIds
    .map((atomId) => {
      const displayIndex = molecule.atoms.findIndex((atom) => atom.id === atomId);
      return displayIndex < 0 ? undefined : displayIndex + 1;
    })
    .filter((displayIndex): displayIndex is number => displayIndex !== undefined);

  return displayIds.length === 0 ? "No selection" : `Selected: ${displayIds.join(", ")}`;
}

export function formatMolFloat(value: number) {
  return value.toFixed(4).padStart(10, " ");
}

export function formatMolInteger(value: number, width: number) {
  return String(value).padStart(width, " ");
}

export function formatMolChargeLines(molecule: Molecule) {
  const entries = molecule.atoms
    .map((atom, index) => ({ atomIndex: index + 1, formalCharge: atom.formalCharge ?? 0 }))
    .filter((entry) => entry.formalCharge !== 0);

  const lines: string[] = [];
  for (let index = 0; index < entries.length; index += 8) {
    const chunk = entries.slice(index, index + 8);
    const values = chunk
      .map((entry) => `${formatMolInteger(entry.atomIndex, 4)}${formatMolInteger(entry.formalCharge, 4)}`)
      .join("");
    lines.push(`M  CHG${formatMolInteger(chunk.length, 3)}${values}`);
  }
  return lines;
}

/**
 * Convert our internal Molecule representation to a MOL string understood by 3dmol.
 */
export function moleculeToMol(molecule: Molecule): string {
  const header = [
    "qm_editor",
    "Generated by qm_editor",
    ""
  ].join("\n");
  const atomCount = molecule.atoms.length;
  const bonds = molecule.bonds || [];
  const bondCount = bonds.length;
  const counts = `${atomCount.toString().padStart(3, " ")}${bondCount.toString().padStart(3, " ")}  0  0  0  0            999 V2000`;
  const atomLines = molecule.atoms.map((atom) => {
    const [x, y, z] = atom.position;
    return `${formatMolFloat(x)}${formatMolFloat(y)}${formatMolFloat(z)} ${atom.element.padEnd(3, " ")} 0  0  0  0  0  0  0  0  0  0  0  0`;
  });
  const bondLines = bonds.map((bond) => {
    const a1Idx = molecule.atoms.findIndex((atom) => atom.id === bond.atomIds[0]) + 1;
    const a2Idx = molecule.atoms.findIndex((atom) => atom.id === bond.atomIds[1]) + 1;
    if (a1Idx <= 0 || a2Idx <= 0) return "";
    return `${a1Idx.toString().padStart(3, " ")}${a2Idx.toString().padStart(3, " ")}${bond.order.toString().padStart(3, " ")}  0  0  0  0`;
  }).filter((line) => line !== "");
  const chargeLines = formatMolChargeLines(molecule);
  return [
    header,
    counts,
    ...atomLines,
    ...bondLines,
    ...chargeLines,
    "M  END",
    ""
  ].join("\n");
}
